version: '3'
services:
    web:
        build:
            context: ./docker/nginx
            dockerfile: Dockerfile
        ports:
            - "10302:80"
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/nginx.conf
            - ./app:/var/www
        links:
            - php
    php:
        build:
            context: ./docker/php
            dockerfile: Dockerfile
        volumes:
            - ./app:/var/www
        links:
            - mysql
    mysql:
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: 'secret'
            MYSQL_USER: 'tutorial'
            MYSQL_PASSWORD: 'secret'
            MYSQL_DATABASE: 'tutorial'
        volumes:
            - mysqldata:/var/lib/mysql
        ports:
            - 3306:3306
volumes:
    mysqldata: {}