app.api:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    prefix: /api

app.view:
    resource:
        path: ../src/Controller/View
        namespace: App\Controller\View
    type: attribute
    prefix: /

app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

api_login_check:
    path: /api/login_check